-- GROUP WARS realtime battles

create table if not exists public.battles (
  id uuid primary key default gen_random_uuid(),
  war_id uuid references public.wars(id) on delete set null,
  attacker_state_id uuid not null references public.states(id) on delete cascade,
  defender_state_id uuid references public.states(id) on delete set null,
  tile_id uuid not null references public.tiles(id) on delete cascade,
  status text not null default 'active' check (status in ('scheduled','active','resolved','cancelled')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null default (now() + interval '3 minutes'),
  last_tick_at timestamptz not null default now(),
  attacker_score integer not null default 0 check (attacker_score >= 0),
  defender_score integer not null default 0 check (defender_score >= 0),
  point_a_owner text check (point_a_owner in ('attacker','defender')),
  point_b_owner text check (point_b_owner in ('attacker','defender')),
  point_c_owner text check (point_c_owner in ('attacker','defender')),
  winner_state_id uuid references public.states(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_one_active_battle_per_tile
  on public.battles(tile_id)
  where status in ('scheduled','active');
create index if not exists idx_battles_attacker on public.battles(attacker_state_id, created_at desc);
create index if not exists idx_battles_defender on public.battles(defender_state_id, created_at desc);

create table if not exists public.battle_players (
  id uuid primary key default gen_random_uuid(),
  battle_id uuid not null references public.battles(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  state_id uuid not null references public.states(id) on delete cascade,
  team text not null check (team in ('attacker','defender')),
  class text not null default 'assault' check (class in ('assault','medic','engineer','scout')),
  hp integer not null default 100 check (hp between 0 and 100),
  point text not null default 'A' check (point in ('A','B','C')),
  kills integer not null default 0,
  deaths integer not null default 0,
  contribution integer not null default 0,
  cooldown_until timestamptz,
  respawn_at timestamptz,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(battle_id, player_id)
);
create index if not exists idx_battle_players_battle on public.battle_players(battle_id);
create index if not exists idx_battle_players_state on public.battle_players(state_id);

create table if not exists public.battle_events (
  id bigint generated by default as identity primary key,
  battle_id uuid not null references public.battles(id) on delete cascade,
  player_id uuid references public.players(id) on delete set null,
  event_type text not null check (event_type in ('join','move','capture','hit','kill','heal','respawn','finish')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_battle_events_battle on public.battle_events(battle_id, id desc);

alter table public.battles enable row level security;
alter table public.battle_players enable row level security;
alter table public.battle_events enable row level security;

drop policy if exists "public read battles" on public.battles;
create policy "public read battles" on public.battles for select to anon, authenticated using (true);
drop policy if exists "public read battle players" on public.battle_players;
create policy "public read battle players" on public.battle_players for select to anon, authenticated using (true);
drop policy if exists "public read battle events" on public.battle_events;
create policy "public read battle events" on public.battle_events for select to anon, authenticated using (true);

grant select on public.battles, public.battle_players, public.battle_events to anon, authenticated;

do $$
begin
  begin alter publication supabase_realtime add table public.battles; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.battle_players; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.battle_events; exception when duplicate_object then null; end;
end $$;
