-- GROUP WARS v0.5 / diplomacy + global world feed

create table if not exists public.diplomacy_relations (
  id uuid primary key default gen_random_uuid(),
  state_a_id uuid not null references public.states(id) on delete cascade,
  state_b_id uuid not null references public.states(id) on delete cascade,
  status text not null check (status in ('alliance_pending','allied','truce_pending','truce','war')),
  requested_by_state_id uuid references public.states(id) on delete set null,
  truce_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (state_a_id <> state_b_id),
  unique(state_a_id, state_b_id)
);

create index if not exists idx_diplomacy_state_a on public.diplomacy_relations(state_a_id, updated_at desc);
create index if not exists idx_diplomacy_state_b on public.diplomacy_relations(state_b_id, updated_at desc);

create table if not exists public.world_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_state_id uuid references public.states(id) on delete set null,
  target_state_id uuid references public.states(id) on delete set null,
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_world_events_created on public.world_events(created_at desc);

alter table public.diplomacy_relations enable row level security;
alter table public.world_events enable row level security;

drop policy if exists "public read diplomacy" on public.diplomacy_relations;
create policy "public read diplomacy" on public.diplomacy_relations for select to anon, authenticated using (true);

drop policy if exists "public read world events" on public.world_events;
create policy "public read world events" on public.world_events for select to anon, authenticated using (true);

grant select on public.diplomacy_relations, public.world_events to anon, authenticated;

do $$
begin
  begin alter publication supabase_realtime add table public.diplomacy_relations; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.world_events; exception when duplicate_object then null; end;
end $$;
