-- GROUP WARS v1.5.0 — complete state-wars specification.
-- Adds the strategy/economy layer from the design brief without replacing the
-- existing realtime 3-point battle gameplay. PostgreSQL remains source of truth.

alter table public.states add column if not exists game_level integer not null default 1 check (game_level between 1 and 100);
alter table public.states add column if not exists max_level integer not null default 50 check (max_level between 1 and 100);
alter table public.states add column if not exists influence bigint not null default 250 check (influence >= 0);
alter table public.states add column if not exists reputation integer not null default 0 check (reputation between -1000 and 1000);
alter table public.states add column if not exists army_power integer not null default 100 check (army_power >= 0);
alter table public.states add column if not exists defense_power integer not null default 100 check (defense_power >= 0);
alter table public.states add column if not exists active_player_count integer not null default 1 check (active_player_count >= 0);
alter table public.states add column if not exists state_size numeric(12,4) not null default 1 check (state_size > 0);
alter table public.states add column if not exists is_beginner_island boolean not null default false;
alter table public.states add column if not exists defense_buffer_base numeric(6,4) not null default 0.08 check (defense_buffer_base between 0 and 0.20);
alter table public.states add column if not exists last_size_refresh_at timestamptz;

alter table public.players add column if not exists last_state_change_at timestamptz;
alter table public.players add column if not exists personal_reputation integer not null default 0;

-- Explicit immutable contribution ledger. state_members.contribution remains the
-- fast aggregate used by existing UI.
create table if not exists public.contribution_events (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  state_id uuid not null references public.states(id) on delete cascade,
  source text not null check (source in ('activity','battle','support','building','defense','alliance','migration')),
  amount integer not null check (amount <> 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_contribution_events_player on public.contribution_events(player_id, created_at desc);
create index if not exists idx_contribution_events_state on public.contribution_events(state_id, created_at desc);

-- Choice-based daily activities. options are declarative so both chat and Mini
-- App render exactly the same choices and server-side rewards.
create table if not exists public.activity_templates (
  key text primary key,
  title text not null,
  description text not null,
  beginner_allowed boolean not null default true,
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.player_activity_runs (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete cascade,
  state_id uuid not null references public.states(id) on delete cascade,
  activity_key text not null references public.activity_templates(key) on delete restrict,
  option_key text not null,
  result_text text not null,
  reward_credits integer not null default 0,
  reward_influence integer not null default 0,
  reward_tech integer not null default 0,
  reward_reputation integer not null default 0,
  reward_contribution integer not null default 0,
  completed_at timestamptz not null default now()
);
create index if not exists idx_player_activity_runs_day on public.player_activity_runs(player_id, completed_at desc);

insert into public.activity_templates(key,title,description,beginner_allowed,options) values
('border_patrol','Патруль границ','На границе замечено подозрительное движение. Выбери способ проверки.',true,
 '[{"key":"forest","label":"Проверить лес","risk":0.20,"credits":150,"influence":8,"tech":0,"reputation":2,"contribution":10},{"key":"road","label":"Перекрыть дорогу","risk":0.10,"credits":120,"influence":12,"tech":0,"reputation":3,"contribution":10},{"key":"locals","label":"Поговорить с жителями","risk":0.05,"credits":80,"influence":16,"tech":0,"reputation":5,"contribution":10}]'::jsonb),
('negotiations','Переговоры','Делегация ждёт ответа. Выбери тон разговора.',true,
 '[{"key":"hard","label":"Жёстко","risk":0.30,"credits":0,"influence":22,"tech":0,"reputation":-2,"contribution":12},{"key":"neutral","label":"Нейтрально","risk":0.10,"credits":0,"influence":15,"tech":0,"reputation":3,"contribution":10},{"key":"friendly","label":"Дружелюбно","risk":0.05,"credits":0,"influence":10,"tech":0,"reputation":7,"contribution":10}]'::jsonb),
('road_repair','Ремонт дороги','Нужно восстановить ключевую дорогу. Реши, как организовать работы.',true,
 '[{"key":"fast","label":"Быстрая бригада","risk":0.25,"credits":180,"influence":0,"tech":2,"reputation":1,"contribution":14},{"key":"balanced","label":"Обычный ремонт","risk":0.10,"credits":140,"influence":0,"tech":4,"reputation":2,"contribution":12},{"key":"quality","label":"Капитальный ремонт","risk":0.05,"credits":100,"influence":0,"tech":6,"reputation":4,"contribution":12}]'::jsonb),
('tax_collection','Сбор налогов','Казне нужны средства. Выбери подход к сбору.',true,
 '[{"key":"fast","label":"Быстро","risk":0.32,"credits":260,"influence":0,"tech":0,"reputation":-3,"contribution":10},{"key":"careful","label":"Аккуратно","risk":0.05,"credits":170,"influence":0,"tech":0,"reputation":3,"contribution":10}]'::jsonb),
('supply_run','Поставка ресурсов','Выбери транспорт для важной поставки.',true,
 '[{"key":"speed","label":"Скоростной катер","risk":0.22,"credits":190,"influence":4,"tech":2,"reputation":1,"contribution":12},{"key":"armored","label":"Бронированный транспорт","risk":0.08,"credits":140,"influence":4,"tech":3,"reputation":2,"contribution":12},{"key":"cargo","label":"Большой грузовик","risk":0.18,"credits":230,"influence":2,"tech":1,"reputation":1,"contribution":12}]'::jsonb),
('espionage','Шпионаж','Попробуй получить разведданные о соседях, рискуя репутацией.',false,
 '[{"key":"quiet","label":"Тихая разведка","risk":0.18,"credits":0,"influence":8,"tech":8,"reputation":-1,"contribution":15},{"key":"deep","label":"Глубокое внедрение","risk":0.38,"credits":0,"influence":14,"tech":14,"reputation":-4,"contribution":18}]'::jsonb),
('diplomatic_mission','Дипломатическая миссия','Представь государство на встрече и выбери тон.',false,
 '[{"key":"hard","label":"Жёсткий","risk":0.24,"credits":0,"influence":24,"tech":0,"reputation":-2,"contribution":14},{"key":"neutral","label":"Нейтральный","risk":0.10,"credits":0,"influence":18,"tech":0,"reputation":3,"contribution":12},{"key":"friendly","label":"Дружелюбный","risk":0.05,"credits":0,"influence":13,"tech":0,"reputation":8,"contribution":12}]'::jsonb)
on conflict (key) do update set title=excluded.title,description=excluded.description,beginner_allowed=excluded.beginner_allowed,options=excluded.options,active=true;

-- Multi-state alliances coexist with the legacy pairwise diplomacy relation.
create table if not exists public.alliances (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  leader_state_id uuid not null references public.states(id) on delete cascade,
  max_members integer not null default 5 check (max_members between 2 and 12),
  resource_sharing_enabled boolean not null default false,
  attack_support_enabled boolean not null default true,
  defense_support_enabled boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.alliance_members (
  alliance_id uuid not null references public.alliances(id) on delete cascade,
  state_id uuid not null references public.states(id) on delete cascade,
  status text not null default 'active' check (status in ('invited','active','leaving')),
  joined_at timestamptz not null default now(),
  primary key (alliance_id,state_id)
);
create unique index if not exists uq_alliance_active_state on public.alliance_members(state_id) where status='active';

-- Strategic metadata around the existing realtime battle.
alter table public.battles add column if not exists battle_type text not null default 'raid';
alter table public.battles drop constraint if exists battles_battle_type_check;
alter table public.battles add constraint battles_battle_type_check check (battle_type in ('raid','siege','territory'));
alter table public.battles add column if not exists attacker_state_size numeric(12,4) not null default 1;
alter table public.battles add column if not exists defender_state_size numeric(12,4) not null default 1;
alter table public.battles add column if not exists attacker_raw_power integer not null default 0;
alter table public.battles add column if not exists defender_raw_power integer not null default 0;
alter table public.battles add column if not exists attacker_final_power integer not null default 0;
alter table public.battles add column if not exists defender_final_power integer not null default 0;
alter table public.battles add column if not exists underdog_bonus numeric(6,4) not null default 0;
alter table public.battles add column if not exists defense_buffer_pct numeric(6,4) not null default 0;
alter table public.battles add column if not exists random_seed bigint;
alter table public.battles add column if not exists attacker_random_modifier numeric(6,4) not null default 1;
alter table public.battles add column if not exists defender_random_modifier numeric(6,4) not null default 1;
alter table public.battles add column if not exists attacker_loss_pct numeric(6,4) not null default 0;
alter table public.battles add column if not exists defender_loss_pct numeric(6,4) not null default 0;
alter table public.battles add column if not exists stolen_budget bigint not null default 0;
alter table public.battles add column if not exists stolen_influence bigint not null default 0;
alter table public.battles add column if not exists strategy_rewards_applied boolean not null default false;

create table if not exists public.battle_supports (
  id uuid primary key default gen_random_uuid(),
  battle_id uuid not null references public.battles(id) on delete cascade,
  state_id uuid not null references public.states(id) on delete cascade,
  side text not null check (side in ('attacker','defender')),
  support_type text not null check (support_type in ('attack','defense')),
  power_given integer not null check (power_given > 0),
  contributed_by_player_id uuid references public.players(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(battle_id,state_id)
);
create index if not exists idx_battle_supports_battle on public.battle_supports(battle_id);

-- Refresh cached state-size and strategic power from real activity and buildings.
create or replace function public.gw_refresh_state_strategy(p_state_id uuid)
returns public.states
language plpgsql
security definer
set search_path=public
as $$
declare
  s public.states%rowtype;
  active_count integer := 1;
  hq_level integer := 1;
  barracks_level integer := 1;
  lab_level integer := 1;
  computed_size numeric := 1;
begin
  select * into s from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;

  select greatest(1,count(*))::integer into active_count
  from public.state_members sm
  join public.players p on p.id=sm.player_id
  where sm.state_id=p_state_id and p.last_seen_at >= now()-interval '7 days';

  select coalesce(max(level),1) into hq_level from public.buildings where state_id=p_state_id and building_type='hq';
  select coalesce(max(level),1) into barracks_level from public.buildings where state_id=p_state_id and building_type='barracks';
  select coalesce(max(level),1) into lab_level from public.buildings where state_id=p_state_id and building_type='lab';

  computed_size := power(active_count::numeric,0.4) * power(greatest(1,hq_level)::numeric,0.6);
  update public.states set
    active_player_count=active_count,
    state_size=greatest(0.0001,computed_size),
    game_level=least(max_level,greatest(1,hq_level + floor((barracks_level+lab_level)/4.0)::integer)),
    army_power=greatest(100,100 + barracks_level*55 + lab_level*10 + floor(rating/30.0)::integer),
    defense_power=greatest(100,100 + hq_level*45 + lab_level*12 + floor(island_integrity*1.5)::integer),
    last_size_refresh_at=now()
  where id=p_state_id
  returning * into s;
  return s;
end;
$$;
revoke all on function public.gw_refresh_state_strategy(uuid) from public,anon,authenticated;
grant execute on function public.gw_refresh_state_strategy(uuid) to service_role;

-- Activity resolution is authoritative and idempotency is enforced by the daily
-- count. Every player may resolve at most four choice activities per UTC day.
create or replace function public.gw_complete_activity(
  p_player_id uuid,
  p_state_id uuid,
  p_activity_key text,
  p_option_key text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  tpl public.activity_templates%rowtype;
  s public.states%rowtype;
  option_data jsonb;
  risk numeric := 0;
  success boolean := true;
  rc integer := 0;
  ri integer := 0;
  rt integer := 0;
  rr integer := 0;
  rcon integer := 0;
  result_message text;
  run_id uuid;
begin
  perform 1 from public.players where id=p_player_id for update;
  if not found then raise exception 'Игрок не найден.'; end if;
  select * into s from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;
  if not exists(select 1 from public.state_members where player_id=p_player_id and state_id=p_state_id) then
    raise exception 'Игрок не состоит в этом государстве.';
  end if;
  if (select count(*) from public.player_activity_runs where player_id=p_player_id and completed_at>=date_trunc('day',now())) >= 4 then
    raise exception 'Сегодня уже выполнено четыре активности.';
  end if;
  if exists(select 1 from public.player_activity_runs where player_id=p_player_id and activity_key=p_activity_key and completed_at>=date_trunc('day',now())) then
    raise exception 'Эта активность уже выполнена сегодня.';
  end if;

  select * into tpl from public.activity_templates where key=p_activity_key and active=true;
  if not found then raise exception 'Активность не найдена.'; end if;
  if s.is_beginner_island and not tpl.beginner_allowed then raise exception 'Эта активность пока недоступна на Острове новичков.'; end if;

  select value into option_data from jsonb_array_elements(tpl.options) where value->>'key'=p_option_key limit 1;
  if option_data is null then raise exception 'Вариант действия не найден.'; end if;

  risk := greatest(0,least(0.8,coalesce((option_data->>'risk')::numeric,0)));
  -- Beginner Island guarantees a safer minimum-success experience.
  if s.is_beginner_island then risk := least(risk,0.08); end if;
  success := random() >= risk;
  rc := coalesce((option_data->>'credits')::integer,0);
  ri := coalesce((option_data->>'influence')::integer,0);
  rt := coalesce((option_data->>'tech')::integer,0);
  rr := coalesce((option_data->>'reputation')::integer,0);
  rcon := coalesce((option_data->>'contribution')::integer,0);

  if not success then
    rc := floor(rc*0.25)::integer; ri := floor(ri*0.25)::integer; rt := floor(rt*0.25)::integer;
    rr := least(rr,-2); rcon := greatest(2,floor(rcon*0.4)::integer);
    result_message := 'План сработал не полностью. Часть награды потеряна из-за риска.';
  else
    result_message := 'Операция выполнена успешно.';
  end if;

  update public.states set credits=credits+greatest(0,rc), influence=influence+greatest(0,ri), tech=tech+greatest(0,rt), reputation=greatest(-1000,least(1000,reputation+rr)) where id=p_state_id;
  update public.state_members set contribution=greatest(0,contribution+rcon) where state_id=p_state_id and player_id=p_player_id;
  update public.players set xp=xp+greatest(2,rcon), personal_reputation=personal_reputation+rr where id=p_player_id;
  insert into public.contribution_events(player_id,state_id,source,amount,metadata) values(p_player_id,p_state_id,'activity',rcon,jsonb_build_object('activity',p_activity_key,'option',p_option_key,'success',success));
  insert into public.player_activity_runs(player_id,state_id,activity_key,option_key,result_text,reward_credits,reward_influence,reward_tech,reward_reputation,reward_contribution)
    values(p_player_id,p_state_id,p_activity_key,p_option_key,result_message,rc,ri,rt,rr,rcon) returning id into run_id;

  return jsonb_build_object('id',run_id,'success',success,'text',result_message,'credits',rc,'influence',ri,'tech',rt,'reputation',rr,'contribution',rcon);
end;
$$;
revoke all on function public.gw_complete_activity(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.gw_complete_activity(uuid,uuid,text,text) to service_role;

-- Strategic battle metadata is generated at the DB boundary so attacks started
-- from Telegram and Mini App cannot diverge.
create or replace function public.gw_prepare_battle_strategy()
returns trigger
language plpgsql
set search_path=public
as $$
declare
  a public.states%rowtype;
  d public.states%rowtype;
  ratio numeric := 1;
  size_log numeric := 0;
  recent_attacks integer := 0;
  aggr numeric := 0;
  rep_bonus numeric := 0;
  seed bigint;
begin
  if new.battle_kind <> 'island' or new.defender_state_id is null then return new; end if;
  select * into a from public.gw_refresh_state_strategy(new.attacker_state_id);
  select * into d from public.gw_refresh_state_strategy(new.defender_state_id);

  if a.is_beginner_island then raise exception 'Атаки с Острова новичков запрещены.'; end if;
  if d.is_beginner_island then raise exception 'Остров новичков находится под защитой.'; end if;

  ratio := greatest(0.0001,a.state_size/greatest(0.0001,d.state_size));
  size_log := greatest(0,ln(ratio)/ln(2.0));
  select count(*)::integer into recent_attacks from public.battles where attacker_state_id=a.id and created_at>=now()-interval '7 days';
  aggr := case when recent_attacks>=3 then least(0.15,(recent_attacks-2)*0.05) else 0 end;
  rep_bonus := greatest(0,least(0.12,d.reputation/5000.0));
  seed := floor(random()*900000000000000000)::bigint + 1000000;

  new.attacker_state_size := a.state_size;
  new.defender_state_size := d.state_size;
  new.attacker_size_modifier := round(1-least(0.30,0.08*size_log),4);
  new.defender_size_modifier := round(1+least(0.25,0.07*size_log),4);
  new.underdog_bonus := round(least(0.25,0.07*size_log),4);
  new.aggression_penalty := round(aggr,4);
  new.defense_buffer_pct := round(least(0.20,d.defense_buffer_base+rep_bonus),4);
  new.attacker_raw_power := a.army_power;
  new.defender_raw_power := d.defense_power;
  new.random_seed := seed;
  new.attacker_random_modifier := round((0.85+random()*0.30)::numeric,4);
  new.defender_random_modifier := round((0.85+random()*0.30)::numeric,4);
  new.attacker_final_power := greatest(1,round(a.army_power*new.attacker_size_modifier*(1-new.aggression_penalty)*new.attacker_random_modifier));
  new.defender_final_power := greatest(1,round((d.defense_power*new.defender_size_modifier*(1+new.defense_buffer_pct))*new.defender_random_modifier));
  return new;
end;
$$;

drop trigger if exists trg_gw_prepare_battle_strategy on public.battles;
create trigger trg_gw_prepare_battle_strategy before insert on public.battles for each row execute function public.gw_prepare_battle_strategy();

-- Voluntary alliance support. One supporting state per battle, capped so allies
-- help but cannot replace the fighting state's own army.
create or replace function public.gw_add_battle_support(
  p_battle_id uuid,
  p_support_state_id uuid,
  p_player_id uuid,
  p_side text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.battles%rowtype;
  support_state public.states%rowtype;
  base_power integer;
  current_support integer := 0;
  cap_power integer;
  granted integer;
  target_state uuid;
begin
  if p_side not in ('attacker','defender') then raise exception 'Некорректная сторона поддержки.'; end if;
  select * into b from public.battles where id=p_battle_id for update;
  if not found or b.status not in ('scheduled','active') then raise exception 'Битва уже недоступна для поддержки.'; end if;
  if not exists(select 1 from public.state_members where state_id=p_support_state_id and player_id=p_player_id and role in ('president','minister','general')) then
    raise exception 'Поддержку может отправить руководство государства.';
  end if;
  if p_support_state_id in (b.attacker_state_id,b.defender_state_id) then raise exception 'Участник боя не считается союзной поддержкой.'; end if;
  select * into support_state from public.gw_refresh_state_strategy(p_support_state_id);
  if support_state.is_beginner_island and p_side='attacker' then raise exception 'Остров новичков может помогать только в обороне.'; end if;

  target_state := case when p_side='attacker' then b.attacker_state_id else b.defender_state_id end;
  if not exists (
    select 1 from public.diplomacy_relations dr
    where ((dr.state_a_id=p_support_state_id and dr.state_b_id=target_state) or (dr.state_b_id=p_support_state_id and dr.state_a_id=target_state))
      and dr.status='allied'
  ) then raise exception 'Поддерживать можно только союзника.'; end if;

  base_power := case when p_side='attacker' then b.attacker_raw_power else b.defender_raw_power end;
  cap_power := greatest(1,floor(base_power*0.35)::integer);
  select coalesce(sum(power_given),0)::integer into current_support from public.battle_supports where battle_id=p_battle_id and side=p_side;
  granted := least(greatest(1,floor((case when p_side='attacker' then support_state.army_power else support_state.defense_power end)*0.15)::integer),greatest(0,cap_power-current_support));
  if granted<=0 then raise exception 'Лимит союзной поддержки для этой стороны уже достигнут.'; end if;

  insert into public.battle_supports(battle_id,state_id,side,support_type,power_given,contributed_by_player_id)
    values(p_battle_id,p_support_state_id,p_side,case when p_side='attacker' then 'attack' else 'defense' end,granted,p_player_id);
  insert into public.contribution_events(player_id,state_id,source,amount,metadata) values(p_player_id,p_support_state_id,'support',greatest(5,granted/20),jsonb_build_object('battleId',p_battle_id,'side',p_side));
  update public.state_members set contribution=contribution+greatest(5,granted/20) where player_id=p_player_id and state_id=p_support_state_id;
  return jsonb_build_object('power',granted,'side',p_side,'cap',cap_power);
end;
$$;
revoke all on function public.gw_add_battle_support(uuid,uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.gw_add_battle_support(uuid,uuid,uuid,text) to service_role;

-- Public read access follows the project's existing read-only Mini App model.
alter table public.contribution_events enable row level security;
alter table public.activity_templates enable row level security;
alter table public.player_activity_runs enable row level security;
alter table public.alliances enable row level security;
alter table public.alliance_members enable row level security;
alter table public.battle_supports enable row level security;

drop policy if exists "public read activity templates" on public.activity_templates;
create policy "public read activity templates" on public.activity_templates for select to anon,authenticated using (active=true);
drop policy if exists "public read alliances" on public.alliances;
create policy "public read alliances" on public.alliances for select to anon,authenticated using (true);
drop policy if exists "public read alliance members" on public.alliance_members;
create policy "public read alliance members" on public.alliance_members for select to anon,authenticated using (true);
drop policy if exists "public read battle supports" on public.battle_supports;
create policy "public read battle supports" on public.battle_supports for select to anon,authenticated using (true);

grant select on public.activity_templates,public.alliances,public.alliance_members,public.battle_supports to anon,authenticated;

-- Optional single beginner state is configured by setting is_beginner_island=true.
-- Keep Freeport distinct: Freeport is a neutral solo hub, Beginner Island is a
-- real protected Telegram chat-state. Enforce the requested level cap when set.
update public.states set max_level=5 where is_beginner_island=true;

-- Useful indexes for balance calculations.
create index if not exists idx_players_last_seen on public.players(last_seen_at desc);
create index if not exists idx_battles_attacker_recent on public.battles(attacker_state_id,created_at desc);

-- Apply the strategic post-battle layer exactly once. Existing v1.4 island
-- integrity/ELO resolution stays intact; this adds limited resource capture,
-- influence loss, loss percentages and recovery protection.
create or replace function public.gw_apply_battle_strategy_rewards(p_battle_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.battles%rowtype;
  a public.states%rowtype;
  d public.states%rowtype;
  attacker_won boolean;
  score_total numeric := 1;
  margin numeric := 0;
  win_loss numeric := 0.10;
  lose_loss numeric := 0.18;
  budget_pct numeric := 0.20;
  influence_pct numeric := 0.15;
  budget_cap bigint := 0;
  budget_take bigint := 0;
  influence_take bigint := 0;
begin
  select * into b from public.battles where id=p_battle_id for update;
  if not found then raise exception 'Битва не найдена.'; end if;
  if b.status <> 'resolved' then raise exception 'Битва ещё не завершена.'; end if;
  if b.strategy_rewards_applied then
    return jsonb_build_object('applied',false,'stolenBudget',b.stolen_budget,'stolenInfluence',b.stolen_influence,'attackerLossPct',b.attacker_loss_pct,'defenderLossPct',b.defender_loss_pct);
  end if;
  if b.defender_state_id is null then
    update public.battles set strategy_rewards_applied=true where id=b.id;
    return jsonb_build_object('applied',true);
  end if;

  perform 1 from public.states where id in (b.attacker_state_id,b.defender_state_id) order by id for update;
  select * into a from public.states where id=b.attacker_state_id;
  select * into d from public.states where id=b.defender_state_id;
  attacker_won := b.winner_state_id=b.attacker_state_id;
  score_total := greatest(1,b.attacker_score+b.defender_score);
  margin := abs(b.attacker_score-b.defender_score)/score_total;
  win_loss := least(0.18,greatest(0.05,0.08+margin*0.12));
  lose_loss := least(0.25,greatest(0.15,0.16+margin*0.16));

  if b.battle_type='siege' then budget_pct:=0.12; influence_pct:=0.10;
  elsif b.battle_type='territory' then budget_pct:=0.08; influence_pct:=0.08;
  end if;

  if attacker_won then
    -- A destroyed island already loses credits in gw_finalize_battle; do not
    -- double-charge it. Influence can still be captured.
    budget_cap := least(5000::bigint,(1000 + a.game_level*300)::bigint);
    if d.destroyed_until is null or d.destroyed_until <= now() then
      budget_take := least(floor(d.credits*budget_pct)::bigint,budget_cap);
    end if;
    influence_take := least(floor(d.influence*influence_pct)::bigint,greatest(50::bigint,budget_cap/10));

    update public.states set
      credits=greatest(0,credits-budget_take),
      influence=greatest(0,influence-influence_take),
      shield_until=greatest(coalesce(shield_until,now()),now()+interval '8 hours')
    where id=d.id;
    update public.states set credits=credits+budget_take,influence=influence+influence_take where id=a.id;

    update public.battles set
      attacker_loss_pct=round(win_loss,4),
      defender_loss_pct=round(lose_loss,4),
      stolen_budget=budget_take,
      stolen_influence=influence_take,
      strategy_rewards_applied=true
    where id=b.id;
  else
    update public.states set shield_until=greatest(coalesce(shield_until,now()),now()+interval '6 hours') where id=a.id;
    update public.battles set
      attacker_loss_pct=round(lose_loss,4),
      defender_loss_pct=round(win_loss,4),
      stolen_budget=0,
      stolen_influence=0,
      strategy_rewards_applied=true
    where id=b.id;
  end if;

  return jsonb_build_object(
    'applied',true,
    'stolenBudget',budget_take,
    'stolenInfluence',influence_take,
    'attackerLossPct',case when attacker_won then win_loss else lose_loss end,
    'defenderLossPct',case when attacker_won then lose_loss else win_loss end
  );
end;
$$;
revoke all on function public.gw_apply_battle_strategy_rewards(uuid) from public,anon,authenticated;
grant execute on function public.gw_apply_battle_strategy_rewards(uuid) to service_role;

-- Include protected Beginner Island status and strategic metrics in the
-- procedural world payload. Rank is global among non-Freeport states; nearby
-- filtering must not reset it to zero.
drop function if exists public.gw_get_islands(double precision,double precision,double precision,integer);
create function public.gw_get_islands(
  p_center_x double precision,
  p_center_y double precision,
  p_radius double precision default 2600,
  p_limit integer default 120
) returns table(
  id uuid,name text,color text,emblem text,world_x double precision,world_y double precision,
  telegram_member_count integer,rating integer,island_wins integer,island_losses integer,
  island_integrity integer,win_streak integer,last_battle_at timestamptz,destroyed_until timestamptz,
  shield_until timestamptz,chat_avatar_file_id text,is_freeport boolean,is_beginner_island boolean,
  game_level integer,max_level integer,influence bigint,reputation integer,army_power integer,defense_power integer,
  active_player_count integer,state_size numeric,rank bigint
)
language sql stable security definer set search_path=public
as $$
  with ranked as (
    select
      s.id,s.name,s.color,coalesce(s.emblem,'◆') as emblem,s.world_x,s.world_y,
      greatest(1,coalesce(s.telegram_member_count,1)) as telegram_member_count,
      greatest(0,coalesce(s.rating,1000)) as rating,
      greatest(0,coalesce(s.island_wins,0)) as island_wins,
      greatest(0,coalesce(s.island_losses,0)) as island_losses,
      greatest(0,least(100,coalesce(s.island_integrity,100))) as island_integrity,
      greatest(0,coalesce(s.win_streak,0)) as win_streak,
      s.last_battle_at,s.destroyed_until,s.shield_until,s.chat_avatar_file_id,
      s.is_freeport,s.is_beginner_island,s.game_level,s.max_level,s.influence,s.reputation,
      s.army_power,s.defense_power,s.active_player_count,s.state_size,s.created_at,
      ((s.world_x-p_center_x)^2+(s.world_y-p_center_y)^2) as distance_sq,
      case when s.is_freeport then 0::bigint else (
        select (1+count(*))::bigint from public.states r
        where not coalesce(r.is_freeport,false) and (
          greatest(0,coalesce(r.rating,1000)) > greatest(0,coalesce(s.rating,1000))
          or (greatest(0,coalesce(r.rating,1000)) = greatest(0,coalesce(s.rating,1000)) and r.created_at < s.created_at)
        )
      ) end as world_rank
    from public.states s
  ), nearby as (
    select * from ranked r
    where r.world_x between p_center_x-greatest(250.0,least(6500.0,p_radius)) and p_center_x+greatest(250.0,least(6500.0,p_radius))
      and r.world_y between p_center_y-greatest(250.0,least(6500.0,p_radius)) and p_center_y+greatest(250.0,least(6500.0,p_radius))
      and r.distance_sq<=power(greatest(250.0,least(6500.0,p_radius)),2)
    order by r.distance_sq asc limit least(greatest(p_limit,1),180)
  )
  select n.id,n.name,n.color,n.emblem,n.world_x,n.world_y,n.telegram_member_count,n.rating,n.island_wins,n.island_losses,
    n.island_integrity,n.win_streak,n.last_battle_at,n.destroyed_until,n.shield_until,n.chat_avatar_file_id,n.is_freeport,n.is_beginner_island,
    n.game_level,n.max_level,n.influence,n.reputation,n.army_power,n.defense_power,n.active_player_count,n.state_size,n.world_rank
  from nearby n order by n.distance_sq asc;
$$;
revoke all on function public.gw_get_islands(double precision,double precision,double precision,integer) from public,anon,authenticated;
grant execute on function public.gw_get_islands(double precision,double precision,double precision,integer) to service_role;

-- ---------------------------------------------------------------------------
-- Beginner Island citizenship, curator, extra infrastructure and hard DB rules.
-- ---------------------------------------------------------------------------

alter table public.players add column if not exists contribution_penalty_until timestamptz;

create table if not exists public.state_membership_history (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  state_id uuid not null references public.states(id) on delete cascade,
  role text not null,
  state_level integer not null default 1,
  joined_at timestamptz,
  left_at timestamptz not null default now()
);
create index if not exists idx_state_membership_history_player on public.state_membership_history(player_id,left_at desc);

-- Keep legacy roles readable while adding the explicit design-brief names.
alter table public.state_members drop constraint if exists state_members_role_check;
alter table public.state_members add constraint state_members_role_check
  check (role in ('president','minister','deputy','general','citizen','member','curator'));

-- Exact design-brief infrastructure is layered onto the existing production
-- buildings so old states remain compatible.
alter table public.buildings drop constraint if exists buildings_building_type_check;
alter table public.buildings add constraint buildings_building_type_check
  check (building_type in ('hq','barracks','mine','refinery','farm','lab','outpost','trade_chamber'));
alter table public.buildings add column if not exists upgrade_started_at timestamptz;
alter table public.buildings add column if not exists upgrade_finishes_at timestamptz;
alter table public.buildings add column if not exists upgrade_target_level integer;
alter table public.buildings add column if not exists upgrade_cooldown_until timestamptz;

insert into public.buildings(state_id,building_type,level)
select s.id,b.kind,1
from public.states s
cross join (values ('outpost'),('trade_chamber')) as b(kind)
on conflict(state_id,building_type) do nothing;

-- Beginner Island never keeps a president and starts with the requested level cap.
update public.states set owner_player_id=null,max_level=5 where is_beginner_island=true;
update public.buildings b set level=least(level,5)
where exists(select 1 from public.states s where s.id=b.state_id and s.is_beginner_island=true);
update public.buildings b set level=1
where b.building_type='barracks'
  and exists(select 1 from public.states s where s.id=b.state_id and s.is_beginner_island=true);

create or replace function public.gw_refresh_beginner_curator(p_state_id uuid)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  s public.states%rowtype;
  curator_id uuid;
begin
  select * into s from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;
  if not s.is_beginner_island then return null; end if;

  update public.states set owner_player_id=null,max_level=5 where id=p_state_id;
  update public.state_members set role='citizen' where state_id=p_state_id and role in ('president','minister','deputy','general','curator');

  select sm.player_id into curator_id
  from public.state_members sm
  join public.players p on p.id=sm.player_id
  where sm.state_id=p_state_id
  order by sm.contribution desc,p.last_seen_at desc,sm.joined_at asc
  limit 1;

  if curator_id is not null then
    update public.state_members set role='curator' where state_id=p_state_id and player_id=curator_id;
  end if;
  return curator_id;
end;
$$;
revoke all on function public.gw_refresh_beginner_curator(uuid) from public,anon,authenticated;
grant execute on function public.gw_refresh_beginner_curator(uuid) to service_role;

-- One active citizenship. State changes are only allowed between Beginner Island
-- and a normal state, once per 24h. Leaving Beginner Island applies the 72h
-- contribution penalty. Returning is restricted to low-level players/states and
-- recent presidents of strong states are excluded.
create or replace function public.gw_set_player_home_state(
  p_player_id uuid,
  p_state_id uuid,
  p_role text,
  p_membership_verified_at timestamptz default null
) returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  membership public.state_members%rowtype;
  player_row public.players%rowtype;
  current_state public.states%rowtype;
  target_state public.states%rowtype;
  previous_member public.state_members%rowtype;
  latest_previous_level integer;
  v_role text:=p_role;
  is_transition boolean:=false;
begin
  select * into player_row from public.players where id=p_player_id for update;
  if not found then raise exception 'Игрок не найден.'; end if;
  select * into target_state from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;

  if v_role not in ('president','minister','deputy','general','citizen','member','curator') then raise exception 'Некорректная роль.'; end if;

  if player_row.home_state_id is not null and player_row.home_state_id<>p_state_id then
    select * into current_state from public.states where id=player_row.home_state_id for update;
    is_transition:=found;
  end if;

  if is_transition then
    -- Freeport is not a citizenship laundering route: once a player actually
    -- leaves one home state, the same 24h transition cooldown follows them.
    if player_row.last_state_change_at is not null and player_row.last_state_change_at>now()-interval '24 hours' then
      raise exception 'Менять государство можно не чаще одного раза в 24 часа.';
    end if;
    if not current_state.is_freeport and not target_state.is_freeport
      and not current_state.is_beginner_island and not target_state.is_beginner_island then
      raise exception 'Прямой переход между обычными государствами запрещён.';
    end if;

    select * into previous_member from public.state_members where state_id=current_state.id and player_id=p_player_id;

    if target_state.is_beginner_island then
      if current_state.is_freeport then
        select h.state_level into latest_previous_level
        from public.state_membership_history h
        where h.player_id=p_player_id
        order by h.left_at desc limit 1;
        if coalesce(latest_previous_level,1)>3 then
          raise exception 'Вернуться на Остров новичков можно только после государства не выше 3 уровня.';
        end if;
      elsif current_state.game_level>3 then
        raise exception 'Вернуться на Остров новичков можно только из государства не выше 3 уровня.';
      end if;
      if exists(
        select 1 from public.state_membership_history h
        where h.player_id=p_player_id and h.role='president' and h.state_level>3 and h.left_at>now()-interval '7 days'
      ) or (not current_state.is_freeport and previous_member.role='president' and current_state.game_level>3) then
        raise exception 'После управления сильным государством Остров новичков недоступен 7 дней.';
      end if;
    end if;

    if not current_state.is_freeport and previous_member.id is not null then
      insert into public.state_membership_history(player_id,state_id,role,state_level,joined_at,left_at)
      values(p_player_id,current_state.id,previous_member.role,greatest(1,current_state.game_level),previous_member.joined_at,now());
    end if;

    update public.players set
      last_state_change_at=now(),
      contribution_penalty_until=case when current_state.is_beginner_island then now()+interval '72 hours' else contribution_penalty_until end
    where id=p_player_id;
  end if;

  if target_state.is_beginner_island then
    v_role:=case when v_role='curator' then 'curator' else 'citizen' end;
    update public.states set owner_player_id=null,max_level=5 where id=target_state.id;
  elsif v_role='curator' then
    v_role:='citizen';
  end if;

  delete from public.state_members where player_id=p_player_id and state_id<>p_state_id;
  insert into public.state_members(state_id,player_id,role,membership_verified_at)
  values(p_state_id,p_player_id,v_role,p_membership_verified_at)
  on conflict(state_id,player_id) do update set role=excluded.role,membership_verified_at=excluded.membership_verified_at
  returning * into membership;
  update public.players set home_state_id=p_state_id where id=p_player_id;
  return membership.id;
end;
$$;
revoke all on function public.gw_set_player_home_state(uuid,uuid,text,timestamptz) from public,anon,authenticated;
grant execute on function public.gw_set_player_home_state(uuid,uuid,text,timestamptz) to service_role;

-- Rebuild the strategic aggregate with the defensive outpost and trade chamber.
create or replace function public.gw_refresh_state_strategy(p_state_id uuid)
returns public.states
language plpgsql
security definer
set search_path=public
as $$
declare
  s public.states%rowtype;
  active_count integer := 1;
  hq_level integer := 1;
  barracks_level integer := 1;
  lab_level integer := 1;
  outpost_level integer := 1;
  trade_level integer := 1;
  computed_level integer := 1;
  computed_size numeric := 1;
begin
  select * into s from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;

  select greatest(1,count(*))::integer into active_count
  from public.state_members sm
  join public.players p on p.id=sm.player_id
  where sm.state_id=p_state_id and p.last_seen_at>=now()-interval '7 days';

  select coalesce(max(level),1) into hq_level from public.buildings where state_id=p_state_id and building_type='hq';
  select coalesce(max(level),1) into barracks_level from public.buildings where state_id=p_state_id and building_type='barracks';
  select coalesce(max(level),1) into lab_level from public.buildings where state_id=p_state_id and building_type='lab';
  select coalesce(max(level),1) into outpost_level from public.buildings where state_id=p_state_id and building_type='outpost';
  select coalesce(max(level),1) into trade_level from public.buildings where state_id=p_state_id and building_type='trade_chamber';

  computed_level:=least(s.max_level,greatest(1,hq_level+floor((barracks_level+lab_level+outpost_level+trade_level)/8.0)::integer));
  computed_size:=power(active_count::numeric,0.4)*power(greatest(1,computed_level)::numeric,0.6);
  update public.states set
    active_player_count=active_count,
    state_size=greatest(0.0001,computed_size),
    game_level=computed_level,
    army_power=greatest(100,100+barracks_level*55+lab_level*10+floor(rating/30.0)::integer),
    defense_power=greatest(100,100+hq_level*45+outpost_level*52+lab_level*12+floor(island_integrity*1.5)::integer),
    defense_buffer_base=least(0.20,0.06+outpost_level*0.012),
    last_size_refresh_at=now()
  where id=p_state_id
  returning * into s;
  return s;
end;
$$;
revoke all on function public.gw_refresh_state_strategy(uuid) from public,anon,authenticated;
grant execute on function public.gw_refresh_state_strategy(uuid) to service_role;

-- Complete timed upgrades idempotently. The project keeps PostgreSQL as the
-- authority, so a serverless instance does not need an in-memory timer.
create or replace function public.gw_finish_building_upgrades(p_state_id uuid)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  completed integer:=0;
begin
  update public.buildings
  set level=greatest(level,coalesce(upgrade_target_level,level)),
      upgrade_started_at=null,
      upgrade_finishes_at=null,
      upgrade_target_level=null,
      upgrade_cooldown_until=now()+interval '5 minutes',
      updated_at=now()
  where state_id=p_state_id
    and upgrade_target_level is not null
    and upgrade_finishes_at is not null
    and upgrade_finishes_at<=now();
  get diagnostics completed = row_count;
  return completed;
end;
$$;
revoke all on function public.gw_finish_building_upgrades(uuid) from public,anon,authenticated;
grant execute on function public.gw_finish_building_upgrades(uuid) to service_role;

-- Building upgrades are timed and have a short per-building cooldown. Costs are
-- reserved atomically when construction starts, preventing double-spend races.
create or replace function public.gw_upgrade_building(
  p_state_id uuid,
  p_building_type text,
  p_credits bigint,
  p_steel bigint,
  p_fuel bigint,
  p_food bigint,
  p_tech bigint
) returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  s public.states%rowtype;
  b public.buildings%rowtype;
  max_building_level integer:=12;
  target_level integer;
  build_minutes integer;
begin
  if least(p_credits,p_steel,p_fuel,p_food,p_tech)<0 then raise exception 'Некорректная стоимость улучшения.'; end if;
  perform public.gw_finish_building_upgrades(p_state_id);
  select * into s from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;
  select * into b from public.buildings where state_id=p_state_id and building_type=p_building_type for update;
  if not found then raise exception 'Здание не найдено.'; end if;

  if s.is_beginner_island then
    max_building_level:=least(5,s.max_level);
    if p_building_type='barracks' then raise exception 'На Острове новичков агрессивные улучшения запрещены.'; end if;
  end if;
  if b.upgrade_target_level is not null and b.upgrade_finishes_at>now() then raise exception 'Это здание уже улучшается.'; end if;
  if b.upgrade_cooldown_until is not null and b.upgrade_cooldown_until>now() then raise exception 'Здание ещё остывает после предыдущего улучшения.'; end if;
  if b.level>=max_building_level then raise exception 'Максимальный уровень здания достигнут.'; end if;
  if s.credits<p_credits or s.steel<p_steel or s.fuel<p_fuel or s.food<p_food or s.tech<p_tech then
    raise exception 'Не хватает ресурсов для улучшения.';
  end if;

  target_level:=b.level+1;
  build_minutes:=least(45,greatest(2,target_level*3));
  update public.states
  set credits=credits-p_credits,steel=steel-p_steel,fuel=fuel-p_fuel,food=food-p_food,tech=tech-p_tech
  where id=p_state_id;
  update public.buildings
  set upgrade_target_level=target_level,upgrade_started_at=now(),
      upgrade_finishes_at=now()+make_interval(mins=>build_minutes),updated_at=now()
  where id=b.id;
  return target_level;
end;
$$;
revoke all on function public.gw_upgrade_building(uuid,text,bigint,bigint,bigint,bigint,bigint) from public,anon,authenticated;
grant execute on function public.gw_upgrade_building(uuid,text,bigint,bigint,bigint,bigint,bigint) to service_role;

-- Replace activity resolver: exactly 3 choices/day on Beginner Island and 4 on
-- normal states, deterministic offers shared by chat/Mini App, safer beginner
-- outcomes and the -10% contribution penalty after leaving the island.
create or replace function public.gw_complete_activity(
  p_player_id uuid,
  p_state_id uuid,
  p_activity_key text,
  p_option_key text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  tpl public.activity_templates%rowtype;
  s public.states%rowtype;
  p public.players%rowtype;
  option_data jsonb;
  risk numeric:=0;
  success boolean:=true;
  rc integer:=0;
  ri integer:=0;
  rt integer:=0;
  rr integer:=0;
  rcon integer:=0;
  result_message text;
  run_id uuid;
  daily_limit integer:=4;
begin
  select * into p from public.players where id=p_player_id for update;
  if not found then raise exception 'Игрок не найден.'; end if;
  select * into s from public.states where id=p_state_id for update;
  if not found then raise exception 'Государство не найдено.'; end if;
  if not exists(select 1 from public.state_members where player_id=p_player_id and state_id=p_state_id) then raise exception 'Игрок не состоит в этом государстве.'; end if;

  daily_limit:=case when s.is_beginner_island then 3 else 4 end;
  if (select count(*) from public.player_activity_runs where player_id=p_player_id and completed_at>=date_trunc('day',now()))>=daily_limit then
    raise exception 'Все ежедневные активности на сегодня уже выполнены.';
  end if;
  if exists(select 1 from public.player_activity_runs where player_id=p_player_id and activity_key=p_activity_key and completed_at>=date_trunc('day',now())) then
    raise exception 'Эта активность уже выполнена сегодня.';
  end if;

  if not exists(
    select 1 from (
      select at.key
      from public.activity_templates at
      where at.active=true and (not s.is_beginner_island or at.beginner_allowed=true)
      order by md5(at.key||':'||p_player_id::text||':'||current_date::text)
      limit daily_limit
    ) offered where offered.key=p_activity_key
  ) then raise exception 'Эта активность не входит в сегодняшний набор.'; end if;

  select * into tpl from public.activity_templates where key=p_activity_key and active=true;
  if not found then raise exception 'Активность не найдена.'; end if;
  select value into option_data from jsonb_array_elements(tpl.options) where value->>'key'=p_option_key limit 1;
  if option_data is null then raise exception 'Вариант действия не найден.'; end if;

  risk:=greatest(0,least(0.8,coalesce((option_data->>'risk')::numeric,0)));
  if s.is_beginner_island then risk:=least(risk,0.08); end if;
  success:=random()>=risk;
  rc:=coalesce((option_data->>'credits')::integer,0);
  ri:=coalesce((option_data->>'influence')::integer,0);
  rt:=coalesce((option_data->>'tech')::integer,0);
  rr:=coalesce((option_data->>'reputation')::integer,0);
  rcon:=coalesce((option_data->>'contribution')::integer,0);

  if not success then
    rc:=floor(rc*0.25)::integer; ri:=floor(ri*0.25)::integer; rt:=floor(rt*0.25)::integer;
    rr:=least(rr,-2); rcon:=greatest(2,floor(rcon*0.4)::integer);
    result_message:=case when s.is_beginner_island then 'Учебная попытка вышла неидеально, но вы сохранили минимальную награду. Подсказка: выбирайте варианты с меньшим риском.' else 'План сработал не полностью. Часть награды потеряна из-за риска.' end;
  else
    result_message:=case when s.is_beginner_island then 'Тренировка прошла успешно. Получены опыт, репутация и вклад.' else 'Операция выполнена успешно.' end;
  end if;

  if p.contribution_penalty_until is not null and p.contribution_penalty_until>now() then rcon:=greatest(1,floor(rcon*0.90)::integer); end if;

  update public.states set credits=credits+greatest(0,rc),influence=influence+greatest(0,ri),tech=tech+greatest(0,rt),reputation=greatest(-1000,least(1000,reputation+rr)) where id=p_state_id;
  update public.state_members set contribution=greatest(0,contribution+rcon) where state_id=p_state_id and player_id=p_player_id;
  update public.players set xp=xp+greatest(2,rcon),personal_reputation=personal_reputation+rr where id=p_player_id;
  insert into public.contribution_events(player_id,state_id,source,amount,metadata) values(p_player_id,p_state_id,'activity',rcon,jsonb_build_object('activity',p_activity_key,'option',p_option_key,'success',success));
  insert into public.player_activity_runs(player_id,state_id,activity_key,option_key,result_text,reward_credits,reward_influence,reward_tech,reward_reputation,reward_contribution)
  values(p_player_id,p_state_id,p_activity_key,p_option_key,result_message,rc,ri,rt,rr,rcon) returning id into run_id;

  return jsonb_build_object('id',run_id,'success',success,'text',result_message,'credits',rc,'influence',ri,'tech',rt,'reputation',rr,'contribution',rcon,'penaltyActive',coalesce(p.contribution_penalty_until>now(),false));
end;
$$;
revoke all on function public.gw_complete_activity(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.gw_complete_activity(uuid,uuid,text,text) to service_role;

-- Leadership rule from the brief: combat/diplomacy support comes from president
-- or deputy; curator is allowed only because Beginner Island has no president.
create or replace function public.gw_add_battle_support(
  p_battle_id uuid,
  p_support_state_id uuid,
  p_player_id uuid,
  p_side text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.battles%rowtype;
  support_state public.states%rowtype;
  base_power integer;
  current_support integer:=0;
  cap_power integer;
  granted integer;
  target_state uuid;
  support_role text;
begin
  if p_side not in ('attacker','defender') then raise exception 'Некорректная сторона поддержки.'; end if;
  select * into b from public.battles where id=p_battle_id for update;
  if not found or b.status not in ('scheduled','active') then raise exception 'Битва уже недоступна для поддержки.'; end if;
  select sm.role into support_role from public.state_members sm where sm.state_id=p_support_state_id and sm.player_id=p_player_id;
  if support_role is null or support_role not in ('president','minister','deputy','curator') then raise exception 'Поддержку может отправить президент, заместитель или куратор.'; end if;
  if p_support_state_id in (b.attacker_state_id,b.defender_state_id) then raise exception 'Участник боя не считается союзной поддержкой.'; end if;
  select * into support_state from public.gw_refresh_state_strategy(p_support_state_id);
  if support_role='curator' and not support_state.is_beginner_island then raise exception 'Куратор действует только на Острове новичков.'; end if;
  if support_state.is_beginner_island and p_side='attacker' then raise exception 'Остров новичков может помогать только в обороне.'; end if;

  target_state:=case when p_side='attacker' then b.attacker_state_id else b.defender_state_id end;
  if not exists(
    select 1 from public.diplomacy_relations dr
    where ((dr.state_a_id=p_support_state_id and dr.state_b_id=target_state) or (dr.state_b_id=p_support_state_id and dr.state_a_id=target_state)) and dr.status='allied'
  ) then raise exception 'Поддерживать можно только союзника.'; end if;

  base_power:=case when p_side='attacker' then b.attacker_raw_power else b.defender_raw_power end;
  cap_power:=greatest(1,floor(base_power*0.35)::integer);
  select coalesce(sum(power_given),0)::integer into current_support from public.battle_supports where battle_id=p_battle_id and side=p_side;
  granted:=least(greatest(1,floor((case when p_side='attacker' then support_state.army_power else support_state.defense_power end)*0.15)::integer),greatest(0,cap_power-current_support));
  if granted<=0 then raise exception 'Лимит союзной поддержки для этой стороны уже достигнут.'; end if;

  insert into public.battle_supports(battle_id,state_id,side,support_type,power_given,contributed_by_player_id)
  values(p_battle_id,p_support_state_id,p_side,case when p_side='attacker' then 'attack' else 'defense' end,granted,p_player_id);
  insert into public.contribution_events(player_id,state_id,source,amount,metadata)
  values(p_player_id,p_support_state_id,'support',greatest(5,granted/20),jsonb_build_object('battleId',p_battle_id,'side',p_side,'training',support_state.is_beginner_island));
  update public.state_members set contribution=contribution+greatest(5,granted/20) where player_id=p_player_id and state_id=p_support_state_id;
  if support_state.is_beginner_island then
    update public.players set xp=xp+greatest(8,granted/15), personal_reputation=personal_reputation+2 where id=p_player_id;
    update public.states set reputation=least(1000,reputation+2) where id=p_support_state_id;
  end if;
  return jsonb_build_object('power',granted,'side',p_side,'cap',cap_power,'training',support_state.is_beginner_island,'xp',case when support_state.is_beginner_island then greatest(8,granted/15) else 0 end,'reputation',case when support_state.is_beginner_island then 2 else 0 end);
end;
$$;
revoke all on function public.gw_add_battle_support(uuid,uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.gw_add_battle_support(uuid,uuid,uuid,text) to service_role;

-- ---------------------------------------------------------------------------
-- Draws: close battles are genuine draws instead of implicit defender wins.
-- ---------------------------------------------------------------------------
alter table public.battles add column if not exists is_draw boolean not null default false;

create or replace function public.gw_finalize_battle(
  p_battle_id uuid,
  p_attacker_score integer,
  p_defender_score integer
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.battles%rowtype;
  winner_id uuid;
  attacker_won boolean:=false;
  battle_draw boolean:=false;
  v_resolved_at timestamptz:=now();
  attacker_rating integer;
  defender_rating integer;
  expected_attacker double precision;
  attacker_delta integer:=0;
  defender_delta integer:=0;
  loot bigint:=0;
  ruined_until timestamptz;
  defender_integrity integer:=100;
  new_integrity integer:=100;
  integrity_damage integer:=0;
  score_margin integer:=0;
  score_total numeric:=1;
  island_destroyed boolean:=false;
  rating_result numeric:=0;
begin
  select * into b from public.battles where id=p_battle_id for update;
  if not found then raise exception 'Битва не найдена.'; end if;
  if b.status in ('resolved','cancelled') then return jsonb_build_object('applied',false,'battle',to_jsonb(b),'isDraw',b.is_draw); end if;

  score_total:=greatest(1,greatest(0,p_attacker_score)+greatest(0,p_defender_score));
  battle_draw:=abs(p_attacker_score-p_defender_score)/score_total<0.05;
  attacker_won:=not battle_draw and p_attacker_score>p_defender_score;
  winner_id:=case when battle_draw then null when attacker_won then b.attacker_state_id else b.defender_state_id end;

  update public.battles set
    status='resolved',attacker_score=greatest(0,p_attacker_score),defender_score=greatest(0,p_defender_score),
    winner_state_id=winner_id,is_draw=battle_draw,resolved_at=v_resolved_at,last_tick_at=v_resolved_at
  where id=b.id returning * into b;

  if b.battle_kind='island' then
    if b.defender_state_id is null then raise exception 'У островной битвы нет защитника.'; end if;
    perform 1 from public.states where id in (b.attacker_state_id,b.defender_state_id) order by id for update;
    select rating into attacker_rating from public.states where id=b.attacker_state_id;
    select rating,island_integrity into defender_rating,defender_integrity from public.states where id=b.defender_state_id;
    new_integrity:=defender_integrity;

    expected_attacker:=1.0/(1.0+power(10.0,(defender_rating-attacker_rating)/400.0));
    rating_result:=case when battle_draw then 0.5 when attacker_won then 1.0 else 0.0 end;
    attacker_delta:=round(36.0*(rating_result-expected_attacker))::integer;
    if not battle_draw and attacker_delta=0 then attacker_delta:=case when attacker_won then 1 else -1 end; end if;
    defender_delta:=-attacker_delta;

    update public.states set
      rating=greatest(0,rating+attacker_delta),rating_peak=greatest(rating_peak,greatest(0,rating+attacker_delta)),
      island_wins=island_wins+case when not battle_draw and attacker_won then 1 else 0 end,
      island_losses=island_losses+case when not battle_draw and not attacker_won then 1 else 0 end,
      win_streak=case when battle_draw then 0 when attacker_won then win_streak+1 else 0 end,
      best_win_streak=greatest(best_win_streak,case when not battle_draw and attacker_won then win_streak+1 else 0 end),
      last_battle_at=v_resolved_at
    where id=b.attacker_state_id;

    update public.states set
      rating=greatest(0,rating+defender_delta),rating_peak=greatest(rating_peak,greatest(0,rating+defender_delta)),
      island_wins=island_wins+case when not battle_draw and not attacker_won then 1 else 0 end,
      island_losses=island_losses+case when not battle_draw and attacker_won then 1 else 0 end,
      win_streak=case when battle_draw then 0 when attacker_won then 0 else win_streak+1 end,
      best_win_streak=greatest(best_win_streak,case when not battle_draw and not attacker_won then win_streak+1 else 0 end),
      last_battle_at=v_resolved_at
    where id=b.defender_state_id;

    if attacker_won then
      score_margin:=greatest(0,p_attacker_score-p_defender_score);
      integrity_damage:=least(55,greatest(22,22+floor(score_margin/8.0)::integer));
      new_integrity:=greatest(0,defender_integrity-integrity_damage);
      update public.states set island_integrity=new_integrity where id=b.defender_state_id;
      if new_integrity<=0 then
        island_destroyed:=true;
        -- Resource capture is handled exclusively by gw_apply_battle_strategy_rewards
        -- so the design-brief loot cap can never be bypassed by legacy destruction loot.
        loot:=0;
        ruined_until:=now()+interval '2 hours';
        update public.states set island_integrity=0,destroyed_until=ruined_until,
          shield_until=greatest(coalesce(shield_until,now()),now()+interval '10 hours') where id=b.defender_state_id;
      end if;
    end if;

    return jsonb_build_object('applied',true,'battle',to_jsonb(b),'battleKind','island','isDraw',battle_draw,
      'attackerRatingDelta',attacker_delta,'defenderRatingDelta',defender_delta,'integrityDamage',integrity_damage,
      'defenderIntegrity',new_integrity,'islandDestroyed',island_destroyed,'lootCredits',loot,
      'destroyedStateId',case when island_destroyed then b.defender_state_id else null end,'destroyedUntil',ruined_until);
  end if;

  if b.war_id is not null then
    update public.wars set status='resolved',winner_state_id=winner_id,attacker_power=greatest(0,p_attacker_score),
      defender_power=greatest(0,p_defender_score),resolved_at=v_resolved_at where id=b.war_id;
  end if;
  if not battle_draw and attacker_won then
    update public.tiles set owner_state_id=b.attacker_state_id,defense=2,is_capital=false where id=b.tile_id;
    update public.states set rating=rating+35,rating_peak=greatest(rating_peak,rating+35),credits=credits+350 where id=b.attacker_state_id;
  elsif not battle_draw then
    update public.tiles set defense=least(8,defense+1) where id=b.tile_id;
    update public.states set rating=greatest(0,rating-8) where id=b.attacker_state_id;
  end if;
  return jsonb_build_object('applied',true,'battle',to_jsonb(b),'battleKind','territory','isDraw',battle_draw);
end;
$$;
revoke all on function public.gw_finalize_battle(uuid,integer,integer) from public,anon,authenticated;
grant execute on function public.gw_finalize_battle(uuid,integer,integer) to service_role;

create or replace function public.gw_apply_battle_strategy_rewards(p_battle_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.battles%rowtype;
  a public.states%rowtype;
  d public.states%rowtype;
  attacker_won boolean;
  score_total numeric:=1;
  margin numeric:=0;
  win_loss numeric:=0.10;
  lose_loss numeric:=0.18;
  budget_pct numeric:=0.20;
  influence_pct numeric:=0.15;
  budget_cap bigint:=0;
  budget_take bigint:=0;
  influence_take bigint:=0;
  a_recovery bigint:=0;
  d_recovery bigint:=0;
begin
  select * into b from public.battles where id=p_battle_id for update;
  if not found then raise exception 'Битва не найдена.'; end if;
  if b.status<>'resolved' then raise exception 'Битва ещё не завершена.'; end if;
  if b.strategy_rewards_applied then return jsonb_build_object('applied',false,'stolenBudget',b.stolen_budget,'stolenInfluence',b.stolen_influence,'attackerLossPct',b.attacker_loss_pct,'defenderLossPct',b.defender_loss_pct,'isDraw',b.is_draw); end if;
  if b.defender_state_id is null then update public.battles set strategy_rewards_applied=true where id=b.id; return jsonb_build_object('applied',true); end if;

  perform 1 from public.states where id in (b.attacker_state_id,b.defender_state_id) order by id for update;
  select * into a from public.states where id=b.attacker_state_id;
  select * into d from public.states where id=b.defender_state_id;

  if b.is_draw or b.winner_state_id is null then
    a_recovery:=least(1500::bigint,floor(a.credits*0.04)::bigint);
    d_recovery:=least(1500::bigint,floor(d.credits*0.04)::bigint);
    update public.states set credits=greatest(0,credits-a_recovery),shield_until=greatest(coalesce(shield_until,now()),now()+interval '4 hours') where id=a.id;
    update public.states set credits=greatest(0,credits-d_recovery),shield_until=greatest(coalesce(shield_until,now()),now()+interval '4 hours') where id=d.id;
    update public.battles set attacker_loss_pct=0.12,defender_loss_pct=0.12,stolen_budget=0,stolen_influence=0,strategy_rewards_applied=true where id=b.id;
    return jsonb_build_object('applied',true,'isDraw',true,'stolenBudget',0,'stolenInfluence',0,'attackerLossPct',0.12,'defenderLossPct',0.12,'attackerRecoveryCost',a_recovery,'defenderRecoveryCost',d_recovery);
  end if;

  attacker_won:=b.winner_state_id=b.attacker_state_id;
  score_total:=greatest(1,b.attacker_score+b.defender_score);
  margin:=abs(b.attacker_score-b.defender_score)/score_total;
  win_loss:=least(0.18,greatest(0.05,0.08+margin*0.12));
  lose_loss:=least(0.25,greatest(0.15,0.16+margin*0.16));
  if b.battle_type='siege' then budget_pct:=0.12; influence_pct:=0.10;
  elsif b.battle_type='territory' then budget_pct:=0.08; influence_pct:=0.08; end if;

  if attacker_won then
    budget_cap:=least(5000::bigint,(1000+a.game_level*300)::bigint);
    budget_take:=least(floor(d.credits*budget_pct)::bigint,budget_cap);
    influence_take:=least(floor(d.influence*influence_pct)::bigint,greatest(50::bigint,budget_cap/10));
    update public.states set credits=greatest(0,credits-budget_take),influence=greatest(0,influence-influence_take),shield_until=greatest(coalesce(shield_until,now()),now()+interval '8 hours') where id=d.id;
    update public.states set credits=credits+budget_take,influence=influence+influence_take where id=a.id;
    update public.battles set attacker_loss_pct=round(win_loss,4),defender_loss_pct=round(lose_loss,4),stolen_budget=budget_take,stolen_influence=influence_take,strategy_rewards_applied=true where id=b.id;
  else
    update public.states set shield_until=greatest(coalesce(shield_until,now()),now()+interval '6 hours') where id=a.id;
    update public.battles set attacker_loss_pct=round(lose_loss,4),defender_loss_pct=round(win_loss,4),stolen_budget=0,stolen_influence=0,strategy_rewards_applied=true where id=b.id;
  end if;
  return jsonb_build_object('applied',true,'isDraw',false,'stolenBudget',budget_take,'stolenInfluence',influence_take,
    'attackerLossPct',case when attacker_won then win_loss else lose_loss end,'defenderLossPct',case when attacker_won then lose_loss else win_loss end);
end;
$$;
revoke all on function public.gw_apply_battle_strategy_rewards(uuid) from public,anon,authenticated;
grant execute on function public.gw_apply_battle_strategy_rewards(uuid) to service_role;
